### ISSUE TITLE
IDE issue

### ISSUE THREAD

**Issue by Shihtzugp** [yanome/PN532-Felica#1]
Hi, can you share the information of IDE (include version) what you using for this project? thanks!

**Comment by yanome** [comment]
Hello, no specific IDE is needed.

This project is a library that you can use in other projects (like this [example](https://github.com/yanome/PN532-Felica/blob/master/example/felica-read.ino)).

I use [arduino-cli](https://github.com/arduino/arduino-cli) for compiling my sketches. For example:
```
arduino-cli compile -b {your board FQBN} --library /path/to/this/project/ /path/to/your/sketch/
```
